// Code generated by my-constant-generator. DO NOT EDIT.

package twitterscraper

const (

	// Mention JSON Fields

	MentionJSONID = "id"

	MentionJSONUsername = "username"

	MentionJSONName = "name"

	// Url JSON Fields

	UrlJSONDisplayURL = "display_url"

	UrlJSONExpandedURL = "expanded_url"

	UrlJSONURL = "url"

	UrlJSONIndices = "indices"

	// Photo JSON Fields

	PhotoJSONID = "id"

	PhotoJSONURL = "url"

	// Video JSON Fields

	VideoJSONID = "id"

	VideoJSONPreview = "preview"

	VideoJSONURL = "url"

	VideoJSONHLSURL = "hls_url"

	// GIF JSON Fields

	GIFJSONID = "id"

	GIFJSONPreview = "preview"

	GIFJSONURL = "url"

	// Tweet JSON Fields

	TweetJSONVersion = "version"

	TweetJSONConversationID = "conversation_id"

	TweetJSONGIFs = "gifs"

	TweetJSONHashtags = "hashtags"

	TweetJSONHTML = "html"

	TweetJSONID = "id"

	TweetJSONInReplyToStatus = "in_reply_to_status"

	TweetJSONInReplyToStatusID = "in_reply_to_status_id"

	TweetJSONIsQuoted = "is_quoted"

	TweetJSONIsPin = "is_pin"

	TweetJSONIsReply = "is_reply"

	TweetJSONIsRetweet = "is_retweet"

	TweetJSONIsSelfThread = "is_self_thread"

	TweetJSONLikes = "likes"

	TweetJSONName = "name"

	TweetJSONMentions = "mentions"

	TweetJSONPermanentURL = "permanent_url"

	TweetJSONPhotos = "photos"

	TweetJSONPlace = "place"

	TweetJSONQuotedStatus = "quoted_status"

	TweetJSONQuotedStatusID = "quoted_status_id"

	TweetJSONReplies = "replies"

	TweetJSONRetweets = "retweets"

	TweetJSONRetweetedStatus = "retweeted_status"

	TweetJSONRetweetedStatusID = "retweeted_status_id"

	TweetJSONText = "text"

	TweetJSONThread = "thread"

	TweetJSONTimeParsed = "time_parsed"

	TweetJSONTimestamp = "timestamp"

	TweetJSONURLs = "urls"

	TweetJSONUserID = "user_id"

	TweetJSONUsername = "username"

	TweetJSONAvatar = "avatar"

	TweetJSONVideos = "videos"

	TweetJSONViews = "views"

	TweetJSONSensitiveContent = "sensitive_content"

	// ProfileResult JSON Fields

	ProfileResultJSONError = "error"

	// ScrappedTweetResult JSON Fields

	ScrappedTweetResultJSONError = "error"

	// ScheduledTweet JSON Fields

	ScheduledTweetJSONID = "id"

	ScheduledTweetJSONState = "state"

	ScheduledTweetJSONExecuteAt = "execute_at"

	ScheduledTweetJSONText = "text"

	ScheduledTweetJSONVideos = "videos"

	ScheduledTweetJSONPhotos = "photos"

	ScheduledTweetJSONGIFs = "gifs"

	// ExtendedMedia JSON Fields

	ExtendedMediaJSONIDStr = "id_str"

	ExtendedMediaJSONMediaURLHttps = "media_url_https"

	ExtendedMediaJSONExtSensitiveMediaWarning = "ext_sensitive_media_warning"

	ExtendedMediaJSONType = "type"

	ExtendedMediaJSONURL = "url"

	ExtendedMediaJSONVideoInfo = "video_info"

	// Professional JSON Fields

	ProfessionalJSONRestID = "rest_id"

	ProfessionalJSONProfessionalType = "professional_type"

	ProfessionalJSONCategory = "category"

	// UserV2 JSON Fields

	UserV2JSONID = "id"

	UserV2JSONRestID = "rest_id"

	UserV2JSONAffiliatesHighlightLabel = "affiliates_highlighted_label"

	UserV2JSONAvatar = "avatar"

	UserV2JSONCore = "core"

	UserV2JSONDmPermissions = "dm_permissions"

	UserV2JSONFollowedBy = "followed_by"

	UserV2JSONFollowing = "following"

	UserV2JSONHasGraduatedAccess = "has_graduated_access"

	UserV2JSONIsBlueVerified = "is_blue_verified"

	UserV2JSONLegacy = "legacy"

	UserV2JSONLocation = "location"

	UserV2JSONMediaPermissions = "media_permissions"

	UserV2JSONParodyCommentaryFanLabel = "parody_commentary_fan_label"

	UserV2JSONProfileImageShape = "profile_image_shape"

	UserV2JSONProfessional = "professional"

	UserV2JSONProfileBio = "profile_bio"

	UserV2JSONPrivacy = "privacy"

	UserV2JSONRelationshipPerspectives = "relationship_perspectives"

	UserV2JSONTipjarSettings = "tipjar_settings"

	UserV2JSONSuperFollowEligible = "super_follow_eligible"

	UserV2JSONVerification = "verification"

	// legacyUserV2 JSON Fields

	legacyUserV2JSONCreatedAt = "created_at"

	legacyUserV2JSONDescription = "description"

	legacyUserV2JSONEntities = "entities"

	legacyUserV2JSONFavouritesCount = "favourites_count"

	legacyUserV2JSONFollowersCount = "followers_count"

	legacyUserV2JSONFriendsCount = "friends_count"

	legacyUserV2JSONIDStr = "id_str"

	legacyUserV2JSONListedCount = "listed_count"

	legacyUserV2JSONName = "name"

	legacyUserV2JSONLocation = "location"

	legacyUserV2JSONPinnedTweetIdsStr = "pinned_tweet_ids_str"

	legacyUserV2JSONProfileBannerURL = "profile_banner_url"

	legacyUserV2JSONProfileImageURLHTTPS = "profile_image_url_https"

	legacyUserV2JSONProtected = "protected"

	legacyUserV2JSONScreenName = "screen_name"

	legacyUserV2JSONStatusesCount = "statuses_count"

	legacyUserV2JSONVerified = "verified"

	legacyUserV2JSONFollowedBy = "followed_by"

	legacyUserV2JSONFollowing = "following"

	legacyUserV2JSONCanDm = "can_dm"

	legacyUserV2JSONCanMediaTag = "can_media_tag"

	legacyUserV2JSONDefaultProfile = "default_profile"

	legacyUserV2JSONDefaultProfileImage = "default_profile_image"

	legacyUserV2JSONFastFollowersCount = "fast_followers_count"

	legacyUserV2JSONHasCustomTimelines = "has_custom_timelines"

	legacyUserV2JSONIsTranslator = "is_translator"

	legacyUserV2JSONMediaCount = "media_count"

	legacyUserV2JSONNeedsPhoneVerification = "needs_phone_verification"

	legacyUserV2JSONNormalFollowersCount = "normal_followers_count"

	legacyUserV2JSONPossiblySensitive = "possibly_sensitive"

	legacyUserV2JSONProfileInterstitialType = "profile_interstitial_type"

	legacyUserV2JSONTranslatorType = "translator_type"

	legacyUserV2JSONWantRetweets = "want_retweets"

	legacyUserV2JSONWithheldInCountries = "withheld_in_countries"

	// legacyTweet JSON Fields

	legacyTweetJSONConversationIDStr = "conversation_id_str"

	legacyTweetJSONCreatedAt = "created_at"

	legacyTweetJSONFavoriteCount = "favorite_count"

	legacyTweetJSONFullText = "full_text"

	legacyTweetJSONEntities = "entities"

	legacyTweetJSONExtendedEntities = "extended_entities"

	legacyTweetJSONIDStr = "id_str"

	legacyTweetJSONInReplyToStatusIDStr = "in_reply_to_status_id_str"

	legacyTweetJSONPlace = "place"

	legacyTweetJSONReplyCount = "reply_count"

	legacyTweetJSONRetweetCount = "retweet_count"

	legacyTweetJSONRetweetedStatusIDStr = "retweeted_status_id_str"

	legacyTweetJSONRetweetedStatusResult = "retweeted_status_result"

	legacyTweetJSONQuotedStatusIDStr = "quoted_status_id_str"

	legacyTweetJSONSelfThread = "self_thread"

	legacyTweetJSONTime = "time"

	legacyTweetJSONUserIDStr = "user_id_str"

	legacyTweetJSONViews = "ext_views"

	// Place JSON Fields

	PlaceJSONID = "id"

	PlaceJSONPlaceType = "place_type"

	PlaceJSONName = "name"

	PlaceJSONFullName = "full_name"

	PlaceJSONCountryCode = "country_code"

	PlaceJSONCountry = "country"

	PlaceJSONBoundingBox = "bounding_box"

	// legacyExtendedProfile JSON Fields

	legacyExtendedProfileJSONBirthdate = "birthdate"

	// verificationInfo JSON Fields

	verificationInfoJSONIsIdentityVerified = "is_identity_verified"

	verificationInfoJSONReason = "reason"

	// highlightsInfo JSON Fields

	highlightsInfoJSONCanHighlightTweets = "can_highlight_tweets"

	highlightsInfoJSONHighlightedTweets = "highlighted_tweets"
)
